<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mesh_path" value="package://wasp_gazebo/meshes/"/>

  <xacro:property name="r_a" value="0.075"/>
  <xacro:property name="r_p" value="0.2794"/>
  <xacro:property name="r_l" value="0.074"/>

  <xacro:property name="del_p" value="${[pi, 0, -pi / 3, 2 * pi / 3, 4 * pi / 3, pi / 3]}"/>
  <xacro:property name="del_l" value="${pi/5.9}"/>

  <xacro:property name="index" value="0"/>

  <link name="base_link" rpy="0 0 0">
    <inertial>
      <origin xyz="0.00158 0.00084 -0.06501" rpy="0 0 0"/>
      <mass value="2.6121"/>
      <inertia ixx="0.03" ixy="0.0" ixz="0.0" iyy="0.032" iyz="0.0" izz="0.0050"/>
    </inertial>
    <!--
    <collision name="frame">
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.3"/>
      </geometry>
    </collision>
    -->
    <collision name="rollcage">
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.09" radius="0.14"/>
      </geometry>
    </collision>
    <collision name="lander">
      <origin xyz="0 0 -0.22" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.16"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}WASP_CORE.dae"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}WASP_TOP.dae"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="0 0 -0.002" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}WASP_CAGE.dae"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="0 0 -0.14" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}WASP_EXTRUDER_MOUNT.dae"/>
      </geometry>
    </visual>

    <xacro:macro name="arm" params="del_p:=^">
      <xacro:if value="${del_p}">
        <xacro:property name="theta" value="${del_p.pop(0)}"/>
        <xacro:property name="index" value="${6 - len(del_p)}"/>
        <visual name="arm_${index}">
          <origin xyz="${r_a * cos(theta)} ${r_a * sin(theta)} -0.0062" rpy="0 0 ${theta + pi / 2}"/>
          <geometry>
            <mesh filename="${mesh_path}WASP_ARM.dae"/>
          </geometry>
          <material name="black"/>
        </visual>
        <visual name="motor_${index}">
          <origin xyz="${r_p * cos(theta)} ${r_p * sin(theta)} -0.0062" rpy="0 0 0"/>
          <geometry>
            <mesh filename="${mesh_path}WASP_MOTOR.dae"/>
          </geometry>
          <material name="black"/>
        </visual>
        <xacro:arm/>
      </xacro:if>
    </xacro:macro>
    <xacro:arm del_p="${list(del_p)}"/>

    <xacro:macro name="leg" params="prefix theta">
      <visual name="leg_${prefix}">
        <origin xyz="${r_l * cos(theta)} ${r_l * sin(theta)} -0.206" rpy="0 0 ${theta + pi / 2}"/>
        <geometry>
          <mesh filename="${mesh_path}WASP_LEG.dae"/>
        </geometry>
        <material name="black"/>
      </visual>
    </xacro:macro>
    <xacro:leg prefix="0" theta="${del_l}"/>
    <xacro:leg prefix="1" theta="${-del_l}"/>
    <xacro:leg prefix="2" theta="${pi + del_l}"/>
    <xacro:leg prefix="3" theta="${pi - del_l}"/>

    <xacro:macro name="cargo" params="prefix reflect">
      <visual name="cannister_${prefix}">
        <origin xyz="${0.08 * reflect} -0.076 -0.112" rpy="${-pi/2} 0 0"/>
        <geometry>
          <mesh filename="${mesh_path}WASP_CANNISTER.dae"/>
        </geometry>
        <material name="white"/>
      </visual>
    </xacro:macro>
    <xacro:cargo prefix="0" reflect="1" />
    <xacro:cargo prefix="1" reflect="-1" />
  </link>

  <link name="nozzle_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="${mesh_path}WASP_NOZZLE.dae"/>
      </geometry>
    </visual>
  </link>
  <joint name="nozzle_joint" type="fixed">
    <parent link="base_link"/>
    <child link="nozzle_link"/>
    <origin xyz="-0.059 0.023 -0.286" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="rotor" params="del_p:=^">
    <xacro:if value="${del_p}">
      <xacro:property name="theta" value="${del_p.pop(0)}"/>
      <xacro:property name="index" value="${6 - len(del_p)}"/>

      <joint name="rotor_${index}_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rotor_${index}"/>
        <origin xyz="${r_p * cos(theta)} ${r_p * sin(theta)} 0.029" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.004"/>
      </joint>

      <link name="rotor_${index}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder length="0.01" radius="0.13"/>
<!--             <box size="0.25 0.035 0.01"/> -->
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.025"/>
          <inertia ixx="9.750e-06" ixy="0.0" ixz="0.0" iyy="166.7e-06" iyz="0.0" izz="166.7e-06"/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <xacro:if value="${index == 1 or index == 3 or index == 4}">
            <geometry>
              <mesh filename="${mesh_path}WASP_PROP_CW.dae"/>
            </geometry>
            <material name="blue"/>
          </xacro:if>
          <xacro:if value="${index == 0 or index == 2 or index == 5}">
            <geometry>
              <mesh filename="${mesh_path}WASP_PROP_CCW.dae"/>
            </geometry>
            <material name="red"/>
          </xacro:if>
        </visual>
      </link>

      <xacro:rotor/>
    </xacro:if>
  </xacro:macro>
  <xacro:rotor del_p="${list(del_p)}"/>
</robot>
