<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mesh_path" value="package://wasp_gazebo/meshes/"/>

  <xacro:property name="r_a" value="0.075"/>
  <xacro:property name="r_p" value="0.277"/>
  <xacro:property name="r_l" value="0.092"/>

  <xacro:property name="del_p" value="${[0, pi, pi / 3, 4 * pi / 3, 2 * pi / 3, 5 * pi / 3]}"/>
  <xacro:property name="del_l" value="${pi/6.2}"/>

  <xacro:property name="idx" value="0"/>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 -0.05" rpy="0 0 0"/>
      <mass value="1.6"/>
      <inertia ixx="0.0177" ixy="0.0" ixz="0.0" iyy="0.016" iyz="0.0" izz="0.0025"/>
    </inertial>
    <!--
    <collision name="frame">
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.3"/>
      </geometry>
    </collision>
    <collision name="rollcage">
      <origin xyz="0 0 0.066" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="0.10"/>
      </geometry>
    </collision>
    -->
    <collision name="lander">
      <origin xyz="0 0 -0.08" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.16"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}wasp_core.dae"/>
      </geometry>
    </visual>

    <xacro:macro name="arm" params="del_p:=^">
      <xacro:if value="${del_p}">
        <xacro:property name="theta" value="${del_p.pop(0)}"/>
        <xacro:property name="idx" value="${6 - len(del_p)}"/>
        <visual name="arm_${idx}">
          <origin xyz="${r_a * cos(theta)} ${r_a * sin(theta)} 0.0125" rpy="0 0 ${theta + pi / 2}"/>
          <geometry>
            <mesh filename="${mesh_path}wasp_arm.dae"/>
          </geometry>
          <material name="black"/>
        </visual>
        <visual name="motor_${idx}">
          <origin xyz="${r_p * cos(theta)} ${r_p * sin(theta)} 0.0125" rpy="0 0 0"/>
          <geometry>
            <mesh filename="${mesh_path}wasp_motor.dae"/>
          </geometry>
          <material name="black"/>
        </visual>
        <xacro:arm/>
      </xacro:if>
    </xacro:macro>
    <xacro:arm del_p="${list(del_p)}"/>

    <xacro:macro name="leg" params="prefix theta">
      <visual name="leg_${prefix}">
        <origin xyz="${r_l * cos(theta)} ${r_l * sin(theta)} -0.063" rpy="0 0 ${theta + pi / 2}"/>
        <geometry>
          <mesh filename="${mesh_path}wasp_leg.dae"/>
        </geometry>
        <material name="black"/>
      </visual>
    </xacro:macro>
    <xacro:leg prefix="0" theta="${del_l}"/>
    <xacro:leg prefix="1" theta="${-del_l}"/>
    <xacro:leg prefix="2" theta="${pi + del_l}"/>
    <xacro:leg prefix="3" theta="${pi - del_l}"/>

    <xacro:macro name="cargo" params="prefix reflect">
      <visual name="rod_${prefix}">
        <origin xyz="${0.037 * reflect} 0 -0.036" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_path}wasp_support_rod.dae"/>
        </geometry>
        <material name="black"/>
      </visual>
      <visual name="cannister_${prefix}">
        <origin xyz="${0.063 * reflect} -0.076 -0.074" rpy="${-pi/2} 0 0"/>
        <geometry>
          <mesh filename="${mesh_path}wasp_cannister.dae"/>
        </geometry>
        <material name="white"/>
      </visual>
    </xacro:macro>
    <xacro:cargo prefix="0" reflect="1" />
    <xacro:cargo prefix="1" reflect="-1" />
  </link>

  <xacro:macro name="rotor" params="del_p:=^">
    <xacro:if value="${del_p}">
      <xacro:property name="theta" value="${del_p.pop(0)}"/>
      <xacro:property name="idx" value="${6 - len(del_p)}"/>

      <joint name="rotor_${idx}_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rotor_${idx}"/>
        <origin xyz="${r_p * cos(theta)} ${r_p * sin(theta)} 0.042" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.004"/>
      </joint>

      <link name="rotor_${idx}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder length="0.01" radius="0.13"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.025"/>
          <inertia ixx="9.750e-06" ixy="0.0" ixz="0.0" iyy="166.7e-06" iyz="0.0" izz="166.7e-06"/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <xacro:if value="${idx % 2 == 0}">
            <geometry>
              <mesh filename="${mesh_path}wasp_prop_cw.dae"/>
            </geometry>
            <material name="red"/>
          </xacro:if>
          <xacro:unless value="${idx % 2 == 0}">
            <geometry>
              <mesh filename="${mesh_path}wasp_prop_ccw.dae"/>
            </geometry>
            <material name="blue"/>
          </xacro:unless>
        </visual>
      </link>

      <xacro:rotor/>
    </xacro:if>
  </xacro:macro>
  <xacro:rotor del_p="${list(del_p)}"/>
</robot>
